Ordersproducts:
    type: entity
    table: ordersProducts
    id:
        fkOrder:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: FK_order
        fkProduct:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            id: true
            column: FK_product
    fields:
        unitprice:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            column: unitPrice
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
