Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        size:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
        adddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: addDate
    lifecycleCallbacks: {  }
